# Generated by Django 2.2.3 on 2019-08-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cat_slug',
            field=models.SlugField(blank=True, max_length=500, null=True),
        ),
    ]
