# Generated by Django 2.2.3 on 2019-08-16 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_category_cat_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='cat_slug',
            new_name='slug',
        ),
    ]
